### ISSUE TITLE
Add clang-format / tidy?

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#96]
Shall we create a clang-format config that roughly matches the current code, and enforce it with a linting CI?

**Comment by bnoordhuis** [comment]
Yes, good idea.

**Comment by bnoordhuis** [comment]
I cobbled together a .clang-format that tries to hew close to the existing style but, even disregarding whitespace changes, it results in _massive_ churn:
```bash
$ clang-format -i quickjs*.[ch] lib*.[ch] # clang-format 15
$ git diff --shortstat
 14 files changed, 18373 insertions(+), 18470 deletions(-)
$ git diff --shortstat -w
 13 files changed, 8272 insertions(+), 8369 deletions(-)
```

<details>

```yaml
Language: Cpp
ColumnLimit: 80
IndentWidth: 4
MaxEmptyLinesToKeep: 1
PointerAlignment: Right

AlignAfterOpenBracket: Align
AlignTrailingComments: true

AlignConsecutiveAssignments:
  Enabled:          true
  AcrossEmptyLines: true
  AcrossComments:   true
  AlignCompound:    true
  PadOperators:     true

AlignConsecutiveBitFields:
  Enabled:          true
  AcrossEmptyLines: true
  AcrossComments:   true
  AlignCompound:    true
  PadOperators:     true

AlignConsecutiveDeclarations:
  Enabled:          true
  AcrossEmptyLines: true
  AcrossComments:   true
  AlignCompound:    true
  PadOperators:     true

AlignConsecutiveMacros:
  Enabled:          true
  AcrossEmptyLines: true
  AcrossComments:   true
  AlignCompound:    true
  PadOperators:     true

AllowShortFunctionsOnASingleLine: false

AttributeMacros:
  - __exception
  - __js_printf_like
  - __maybe_unused

BinPackArguments: true
BinPackParameters: true

BreakBeforeBraces: Custom
BraceWrapping:
  AfterCaseLabel:        false
  AfterClass:            false
  AfterControlStatement: Never
  AfterEnum:             false
  AfterFunction:         true
  AfterNamespace:        false
  AfterObjCDeclaration:  false
  AfterStruct:           false
  AfterUnion:            false
  AfterExternBlock:      false
  BeforeCatch:           false
  BeforeElse:            false
  BeforeLambdaBody:      false
  BeforeWhile:           false
  IndentBraces:          false
  SplitEmptyFunction:    true
  SplitEmptyRecord:      true
  SplitEmptyNamespace:   true

SpaceBeforeParensOptions:
  AfterControlStatements:       true
  AfterForeachMacros:           true
  AfterFunctionDefinitionName:  true
  AfterFunctionDeclarationName: true
  AfterIfMacros:                true
```

</details>
